# Strip bazel templating in a bootleg fashion

[hololens]
package = "holo/lens-shell/1.0"
before = "cert-manager"

[hololens.shell]
script = '''
sed -i'' -E 's/^(appVersion|version):.*/\1: v1.7.2/g' Chart.template.yaml
mv -v Chart.template.yaml Chart.yaml
'''

[hololens.input]
root = "cert-manager/helm-chart"
files = "**"

[hololens.output]
merge = "replace"
