[hololens]
container = "ghcr.io/hologit/lenses/helm3:latest"

[hololens.helm]
namespace = "ingress-nginx"
release_name = "ingress-nginx"

namespace_fill = true

chart_path = "helm-chart"
value_files = [
    "default-values.yaml",
    "provider-values.yaml",
    "release-values.yaml"
]

[hololens.post_helm]

[hololens.input]
root = "ingress-nginx"
files = "**"

[hololens.output]
merge = "replace"
