[hololens]
container = "ghcr.io/hologit/lenses/kustomize:latest"

[hololens.kustomize]
directory = "release"

[hololens.input]
root = "metrics-server"
files = "**"

[hololens.output]
merge = "replace"
