# See https://www.linode.com/community/questions/19756/how-can-i-deploy-the-kubernetes-metrics-server-on-lke

[hololens]
container = "ghcr.io/hologit/lenses/k8s-patch:latest"
after = "metrics-server"

[hololens.k8s-patch]
script = '''
manifest => {
    const { kind, metadata: { namespace, name }, spec } = manifest

    if ( kind == 'Deployment' && name == 'metrics-server') {
        spec.template.spec.containers[0].args.push(
            '--kubelet-insecure-tls',
        );
    }
}
'''

[hololens.input]
root = "metrics-server"
files = "**"

[hololens.output]
merge = "overlay"
