[hololens]
container = "ghcr.io/hologit/lenses/helm3:latest"

[hololens.helm]
namespace = "prometheus"
release_name = "prometheus"

chart_path = "helm-chart"
value_files = [
    "default-values.yaml",
    "provider-values.yaml",
    "release-values.yaml"
]

[hololens.input]
root = "prometheus"
files = "**"

[hololens.output]
merge = "replace"
