[hololens]
container = "ghcr.io/hologit/lenses/helm3:latest"

[hololens.input]
root = "promtail"
files = "**"

[hololens.output]
merge = "replace"

[hololens.helm]
namespace = "loki"
release_name = "promtail"

chart_path = "helm-chart"
value_files = [
    "default-values.yaml",
    "provider-values.yaml",
    "release-values.yaml"
]
